### ISSUE TITLE
Does not show "GM Secret" option in the Custom menu when Polyglot is installed

### ISSUE THREAD

**Issue by confucianscholar** [schultzcole/FVTT-GM-Secret-Block#4]
**Behaviour:**
When Polyglot is installed, it seems to override the Paragraph menu options and prevent GM Secret Block from adding the GM Secret option to the Custom menu. This does not break GM Secret blocks themselves, and it only seems to affect areas where Polyglot adds its own list of languages to the text editor options.
- Actor and Items text editing is unaffected (Polyglot doesn't apply to these anyways).
- Journals are affected - however, if you disable Polyglot and then add a GM Secret to a Journal, and the re-enable Polyglot, you are no longer able to add new GM Secrets to Journals (the menu option disappears), but the previously added GM Secret block remains untouched.

**Steps to reproduce:**
1. Enable GM Secret Block
2. (optional) Create a journal entry and write a GM Secret block of text
3. Enable Polyglot
4. Click to edit journal entry from step 2, or create a new journal entry
5. (optional with step 2) Observe that the GM Secret block you wrote remains intact
6. Observe that the GM Secret option is no longer present in the Paragraph dropdown menu, while Polyglots language list is present
7. (Optional) observe that Actor and Item sheets are not impacted due to the lack of Polyglot support in these windows

**Expected behaviour:**
- Polyglot and GM Secret block should not interfere with one another

**Test environment**
Foundry 0.7.9 + DnD5e 1.2.3
GM Secret Block v1.0.0
Polyglot 1.4.0
- Reproduced with no other modules active

**Comment by schultzcole** [comment]
Thank you for the thorough report! I suspect this issue is something that will need to be fixed on the polyglot side of things. I'll see if I can get in touch with Kakaroto and make sure.

**Comment by schultzcole** [comment]
@confucianscholar good news! I have worked with Kakaroto to resolve this issue and the newest version of Polyglot should fix this problem. I don't know exactly when Kakaroto plans on releasing it, but keep an eye out for it.
